### ISSUE TITLE
Reproducing evaluation results issue

### ISSUE THREAD

**Issue by ashmalvayani** [LLM360/Analysis360#2]
I'm trying to reproduce the evaluation results via the code provided.

1. Can you please let us know how many GPUs are sufficient for evaluation? I've tried it on A100 8-80GB GPU with batch size 16 (as mentioned in the code), 8, 4, 2, 1 but I'm still getting CUDA OUT OF MEMORY error (I am not using the SLURM so I've commented out that line instead and running directly on a GPU node.)
<img width="888" alt="image" src="https://github.com/LLM360/Analysis360/assets/56957881/0ca8d96f-2e21-42a4-80fa-1780d8c37bc1">

2. In evaluation.py the file "main.py" is used. Can you confirm if that's the file of the other repository "amber-train"?

**Comment by yukiontheiceberg** [comment]
Hey ash, thanks for your questions and we are working on addressing them!

1. I usually run the evals with 1 A100, sometimes 2. We are working on improving the amber eval scripts, trying to separate the slurm args and cmds so that users without slurm can also run evals fine. Details can be found at https://github.com/LLM360/Analysis360/pull/3.
2. yes this is a nice catch, upload it in the PR mentioned above.

**Comment by ashmalvayani** [comment]
1. When I'm trying to reproduce the code, it continuously throws cuda out of memory error even with the batch size of 1. It does loads the evaluation task but gives OOM. Any possible fix to that?
2. I believe the missing main.py is not the same as there in amber-train as that's the code for training only and not the evaluation.

**Comment by yukiontheiceberg** [comment]
1. Did you try with the new code and it still gave you OOM?
2. you are right, I don't think that's the same main.py. This main.py is for amber eval only.

**Comment by ashmalvayani** [comment]
1. The last updated code was 2-3 weeks ago. Are there any further changes after that? I just commented out srun in my version and ran the bash on the GPU node only.
2. There's currently no main.py file in the repo. I see one file in the PR but not in the actual repo.

**Comment by yukiontheiceberg** [comment]
Oh I mentioned above we are fixing both 1 and 2 in https://github.com/LLM360/Analysis360/pull/3. You could try to use the latest dev branch to see whether it resolves your issue.

**Comment by ashmalvayani** [comment]
I am trying the evaluation script from llm-harness directly as you've mentioned in your repository. On the HellaSwag evaluation metric, two sub-metrics are showing up. Can you please confirm which one was picked for evaluation (acc or acc_norm)?

![image](https://github.com/LLM360/Analysis360/assets/56957881/a639ac7e-271d-4f57-92c0-cb5c234871aa)

Similarly, for arc_challenge evaluation, there's no acc_norm, so was "acc" picked for these evaluation tasks? PFA
![image](https://github.com/LLM360/Analysis360/assets/56957881/5e3e883a-3fa2-4598-ba84-230de9c92903)

**Comment by ashmalvayani** [comment]
Hello. I was able to reproduce your code with the dev branch on a single GPU. However, I had the following questions:

1. Is there a way to run on Multi-GPUs locally? By default, it's just running on a single node.
2. Can you let us know which evaluation metric you've used in the paper? 
The results had different metrics. for eg, see the snapshot below.
For MMLU did you take the average of all sub-tasks acc/acc_norm scores? 
For TruthfulQA, did you use only bluert_acc/bleu_acc for both truthfulqa_mc/_gen?
<img width="582" alt="image" src="https://github.com/LLM360/Analysis360/assets/56957881/1e4ffdfc-f2b2-4e61-be72-70e43dd3b872">

**Comment by haonan-li** [comment]
Hi, 
to your question:
1. Since we use slurm workload management system, which will allocate gpus automatically. We don't have multi-gpu script by default. You can refer to official [lm-evaluation-harness](https://github.com/EleutherAI/lm-evaluation-harness) for multi-gpu guideline, this [page](https://github.com/EleutherAI/lm-evaluation-harness/issues/573) may also help.
3. all these details are present in [utils.py](https://github.com/LLM360/Analysis360/blob/main/harness/scripts/utils.py#L111-L152). You can find for each dataset, which metric were we use. Overall, we follow the [open-llm-leaderboard](https://huggingface.co/spaces/HuggingFaceH4/open_llm_leaderboard) setting.

**Comment by yukiontheiceberg** [comment]
Hi, looks like all your issues are resolved, I will close this for now.
